jobs:

- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}

  steps:
  - checkout: self
    submodules: true
  - script: |
      cmake -D CMAKE_C_COMPILER=gcc-8 -D CMAKE_CXX_COMPILER=g++-8 .
      cmake --build .
      java -cp sample1.jar Sample1
    displayName: 'Build & run'
